import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Next.js App Layout",
    template: "%s | Next.js App", // %s will be replaced with the page title
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: "#f8f9fa",
            padding: "10px 20px",
            textAlign: "center",
            fontSize: "24px",
            fontWeight: "bold",
            borderBottom: "1px solid #dee2e6",
          }}
        >
          Header
        </header>
        {children}
        <footer
          style={{
            backgroundColor: "blue",
            padding: "10px 20px",
            textAlign: "center",
            fontSize: "16px",
            borderTop: "1px solid #dee2e6",
            position: "fixed",
            width: "100%",
            bottom: 0,
            margin: "none",
          }}
        >
          Footer
        </footer>
      </body>
    </html>
  );
}
